1. Importing packages and creating folders

In [1]:
from pathlib import Path
import subprocess
import json
import pandas as pd
import numpy as np

import matplotlib
import matplotlib.pyplot as plt

raw_dir = Path("data/subset_raw")
clean_dir = Path("data/clean")
report_dir = Path("data/fastp_reports")
reference_dir = Path("data/reference")
quant_dir = Path("data/quant")
results_dir = Path("results")

for folder in [
    raw_dir,
    clean_dir,
    report_dir,
    reference_dir,
    quant_dir,
    results_dir,
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Project folders are ready.")

Project folders are ready.

2. Retrieving the metadata from the 12 samples

TSV file with TPM valus

In [2]:
ena_url = (
    "https://www.ebi.ac.uk/ena/portal/api/filereport"
    "?accession=PRJNA1194989"
    "&result=read_run"
    "&fields=run_accession,sample_accession,experiment_title,library_layout"
    "&format=tsv"
)

samples = pd.read_csv(ena_url, sep="\t")

samples["sample_name"] = samples["experiment_title"].str.extract(
    r"GSM\d+:\s+(\S+)"
)

samples["condition"] = (
    samples["sample_name"]
    .str.replace(r"_\d+$", "", regex=True)
    .str.replace("624Mel_", "", regex=False)
)

samples["replicate"] = (
    samples["sample_name"]
    .str.extract(r"_(\d+)$")[0]
    .astype(int)
)

samples = samples.sort_values(
    ["condition", "replicate"]
).reset_index(drop=True)

display(
    samples[
        [
            "run_accession",
            "sample_name",
            "condition",
            "replicate",
            "library_layout",
        ]
    ]
)

print("Number of samples:", len(samples))

   run_accession           sample_name    condition  replicate library_layout
0    SRR31631262       624Mel_siCTRL_1       siCTRL          1         PAIRED
1    SRR31631258       624Mel_siCTRL_2       siCTRL          2         PAIRED
2    SRR31631254       624Mel_siCTRL_3       siCTRL          3         PAIRED
3    SRR31631261  624Mel_siCTRL+IFNg_1  siCTRL+IFNg          1         PAIRED
4    SRR31631257  624Mel_siCTRL+IFNg_2  siCTRL+IFNg          2         PAIRED
5    SRR31631253  624Mel_siCTRL+IFNg_3  siCTRL+IFNg          3         PAIRED
6    SRR31631260       624Mel_siMITF_1       siMITF          1         PAIRED
7    SRR31631256       624Mel_siMITF_2       siMITF          2         PAIRED
8    SRR31631252       624Mel_siMITF_3       siMITF          3         PAIRED
9    SRR31631259  624Mel_siMITF+IFNg_1  siMITF+IFNg          1         PAIRED
10   SRR31631255  624Mel_siMITF+IFNg_2  siMITF+IFNg          2         PAIRED
11   SRR31631251  624Mel_siMITF+IFNg_3  siMITF+IFNg          3         PAIRED

Number of samples: 12

3. Downloading 1000000 reads from all 12 samples

SRA files

In [3]:
max_spots = 1_000_000

for run in samples["run_accession"]:
    read1 = raw_dir / f"{run}_1.fastq.gz"
    read2 = raw_dir / f"{run}_2.fastq.gz"

    if read1.exists() and read2.exists():
        print(f"{run}: files already exist — skipping")
        continue

    print(f"Retrieving {max_spots:,} paired spots from {run}...")

    subprocess.run(
        [
            "fastq-dump",
            "-N", "1",
            "-X", str(max_spots),
            "--split-files",
            "--gzip",
            "--outdir", str(raw_dir),
            run,
        ],
        check=True,
    )

print("Subset retrieval complete.")

Retrieving 1,000,000 paired spots from SRR31631262...
Read 1000000 spots for SRR31631262
Written 1000000 spots for SRR31631262
Retrieving 1,000,000 paired spots from SRR31631258...
Read 1000000 spots for SRR31631258
Written 1000000 spots for SRR31631258
Retrieving 1,000,000 paired spots from SRR31631254...
Read 1000000 spots for SRR31631254
Written 1000000 spots for SRR31631254
Retrieving 1,000,000 paired spots from SRR31631261...
Read 1000000 spots for SRR31631261
Written 1000000 spots for SRR31631261
Retrieving 1,000,000 paired spots from SRR31631257...
Read 1000000 spots for SRR31631257
Written 1000000 spots for SRR31631257
Retrieving 1,000,000 paired spots from SRR31631253...
Read 1000000 spots for SRR31631253
Written 1000000 spots for SRR31631253
Retrieving 1,000,000 paired spots from SRR31631260...
Read 1000000 spots for SRR31631260
Written 1000000 spots for SRR31631260
Retrieving 1,000,000 paired spots from SRR31631256...
Read 1000000 spots for SRR31631256
Written 1000000 spots for SRR31631256
Retrieving 1,000,000 paired spots from SRR31631252...
Read 1000000 spots for SRR31631252
Written 1000000 spots for SRR31631252
Retrieving 1,000,000 paired spots from SRR31631259...
Read 1000000 spots for SRR31631259
Written 1000000 spots for SRR31631259
Retrieving 1,000,000 paired spots from SRR31631255...
Read 1000000 spots for SRR31631255
Written 1000000 spots for SRR31631255
Retrieving 1,000,000 paired spots from SRR31631251...
Read 1000000 spots for SRR31631251
Written 1000000 spots for SRR31631251
Subset retrieval complete.

4. Confirming the raw FASTQs; 24 in total, one reverse and one forward FASTQ from each sample

In [4]:
raw_fastqs = sorted(raw_dir.glob("*.fastq.gz"))

print("Raw FASTQ files:", len(raw_fastqs))

assert len(samples) == 12, "Expected 12 samples."
assert len(raw_fastqs) == 24, "Expected 24 paired-end FASTQ files."

for run in samples["run_accession"]:
    assert (raw_dir / f"{run}_1.fastq.gz").exists()
    assert (raw_dir / f"{run}_2.fastq.gz").exists()

print("All 12 paired-end samples are present.")

Raw FASTQ files: 24
All 12 paired-end samples are present.

5. Using FASTP to clean pair end reads; resulting in clean FASTQs and QC reports.

In [5]:
for run in samples["run_accession"]:
    input_r1 = raw_dir / f"{run}_1.fastq.gz"
    input_r2 = raw_dir / f"{run}_2.fastq.gz"

    output_r1 = clean_dir / f"{run}_1.clean.fastq.gz"
    output_r2 = clean_dir / f"{run}_2.clean.fastq.gz"

    json_report = report_dir / f"{run}.fastp.json"
    html_report = report_dir / f"{run}.fastp.html"

    if (
        output_r1.exists()
        and output_r2.exists()
        and json_report.exists()
        and html_report.exists()
    ):
        print(f"{run}: already cleaned — skipping")
        continue

    print(f"Cleaning {run}...")

    subprocess.run(
        [
            "fastp",
            "--in1", str(input_r1),
            "--in2", str(input_r2),
            "--out1", str(output_r1),
            "--out2", str(output_r2),
            "--json", str(json_report),
            "--html", str(html_report),
            "--detect_adapter_for_pe",
            "--thread", "4",
        ],
        check=True,
    )

print("Cleaning complete.")

Cleaning SRR31631262...

Detecting adapter sequence for read1...
>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123312436(98.6499%)
Q30 bases: 120357370(96.2859%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122890277(98.3122%)
Q30 bases: 119404394(95.5235%)

Read1 after filtering:
total reads: 991435
total bases: 123501739
Q20 bases: 122079022(98.848%)
Q30 bases: 119241095(96.5501%)

Read2 after filtering:
total reads: 991435
total bases: 123502701
Q20 bases: 121939913(98.7346%)
Q30 bases: 118621518(96.0477%)

Filtering result:
reads passed filter: 1982870
reads failed due to low quality: 16636
reads failed due to too many N: 0
reads failed due to too short: 494
reads with adapter trimmed: 49237
bases trimmed due to adapters: 903889

Duplication rate: 28.4395%

Insert size peak (evaluated by paired-end reads): 202

JSON report: data/fastp_reports/SRR31631262.fastp.json
HTML report: data/fastp_reports/SRR31631262.fastp.html

fastp --in1 data/subset_raw/SRR31631262_1.fastq.gz --in2 data/subset_raw/SRR31631262_2.fastq.gz --out1 data/clean/SRR31631262_1.clean.fastq.gz --out2 data/clean/SRR31631262_2.clean.fastq.gz --json data/fastp_reports/SRR31631262.fastp.json --html data/fastp_reports/SRR31631262.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 10 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631258...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123368927(98.6951%)
Q30 bases: 120583393(96.4667%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122622187(98.0977%)
Q30 bases: 119036618(95.2293%)

Read1 after filtering:
total reads: 989461
total bases: 123204939
Q20 bases: 121863988(98.9116%)
Q30 bases: 119206507(96.7546%)

Read2 after filtering:
total reads: 989461
total bases: 123207430
Q20 bases: 121496045(98.611%)
Q30 bases: 118118618(95.8697%)

Filtering result:
reads passed filter: 1978922
reads failed due to low quality: 20668
reads failed due to too many N: 0
reads failed due to too short: 410
reads with adapter trimmed: 53044
bases trimmed due to adapters: 1001711

Duplication rate: 25.7227%

Insert size peak (evaluated by paired-end reads): 208

JSON report: data/fastp_reports/SRR31631258.fastp.json
HTML report: data/fastp_reports/SRR31631258.fastp.html

fastp --in1 data/subset_raw/SRR31631258_1.fastq.gz --in2 data/subset_raw/SRR31631258_2.fastq.gz --out1 data/clean/SRR31631258_1.clean.fastq.gz --out2 data/clean/SRR31631258_2.clean.fastq.gz --json data/fastp_reports/SRR31631258.fastp.json --html data/fastp_reports/SRR31631258.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 9 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631254...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123267587(98.6141%)
Q30 bases: 120228420(96.1827%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122963160(98.3705%)
Q30 bases: 119509953(95.608%)

Read1 after filtering:
total reads: 992017
total bases: 123607101
Q20 bases: 122156759(98.8267%)
Q30 bases: 119233971(96.4621%)

Read2 after filtering:
total reads: 992017
total bases: 123606929
Q20 bases: 122061267(98.7495%)
Q30 bases: 118762192(96.0805%)

Filtering result:
reads passed filter: 1984034
reads failed due to low quality: 15596
reads failed due to too many N: 0
reads failed due to too short: 370
reads with adapter trimmed: 41404
bases trimmed due to adapters: 833868

Duplication rate: 27.6124%

Insert size peak (evaluated by paired-end reads): 203

JSON report: data/fastp_reports/SRR31631254.fastp.json
HTML report: data/fastp_reports/SRR31631254.fastp.html

fastp --in1 data/subset_raw/SRR31631254_1.fastq.gz --in2 data/subset_raw/SRR31631254_2.fastq.gz --out1 data/clean/SRR31631254_1.clean.fastq.gz --out2 data/clean/SRR31631254_2.clean.fastq.gz --json data/fastp_reports/SRR31631254.fastp.json --html data/fastp_reports/SRR31631254.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 10 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631261...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123226607(98.5813%)
Q30 bases: 120168860(96.1351%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122793414(98.2347%)
Q30 bases: 119167759(95.3342%)

Read1 after filtering:
total reads: 991068
total bases: 123439362
Q20 bases: 121962429(98.8035%)
Q30 bases: 119033855(96.431%)

Read2 after filtering:
total reads: 991068
total bases: 123439921
Q20 bases: 121785683(98.6599%)
Q30 bases: 118333291(95.8631%)

Filtering result:
reads passed filter: 1982136
reads failed due to low quality: 17420
reads failed due to too many N: 0
reads failed due to too short: 444
reads with adapter trimmed: 48602
bases trimmed due to adapters: 939059

Duplication rate: 27.5919%

Insert size peak (evaluated by paired-end reads): 187

JSON report: data/fastp_reports/SRR31631261.fastp.json
HTML report: data/fastp_reports/SRR31631261.fastp.html

fastp --in1 data/subset_raw/SRR31631261_1.fastq.gz --in2 data/subset_raw/SRR31631261_2.fastq.gz --out1 data/clean/SRR31631261_1.clean.fastq.gz --out2 data/clean/SRR31631261_2.clean.fastq.gz --json data/fastp_reports/SRR31631261.fastp.json --html data/fastp_reports/SRR31631261.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 8 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631257...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123276113(98.6209%)
Q30 bases: 120405692(96.3246%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122786624(98.2293%)
Q30 bases: 119166736(95.3334%)

Read1 after filtering:
total reads: 990939
total bases: 123374048
Q20 bases: 121965843(98.8586%)
Q30 bases: 119231329(96.6421%)

Read2 after filtering:
total reads: 990939
total bases: 123375498
Q20 bases: 121733347(98.669%)
Q30 bases: 118299173(95.8855%)

Filtering result:
reads passed filter: 1981878
reads failed due to low quality: 17618
reads failed due to too many N: 0
reads failed due to too short: 504
reads with adapter trimmed: 53006
bases trimmed due to adapters: 1035368

Duplication rate: 27.5736%

Insert size peak (evaluated by paired-end reads): 208

JSON report: data/fastp_reports/SRR31631257.fastp.json
HTML report: data/fastp_reports/SRR31631257.fastp.html

fastp --in1 data/subset_raw/SRR31631257_1.fastq.gz --in2 data/subset_raw/SRR31631257_2.fastq.gz --out1 data/clean/SRR31631257_1.clean.fastq.gz --out2 data/clean/SRR31631257_2.clean.fastq.gz --json data/fastp_reports/SRR31631257.fastp.json --html data/fastp_reports/SRR31631257.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 9 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631253...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123274722(98.6198%)
Q30 bases: 120325143(96.2601%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 120748867(96.5991%)
Q30 bases: 114179661(91.3437%)

Read1 after filtering:
total reads: 985779
total bases: 122812874
Q20 bases: 121438913(98.8813%)
Q30 bases: 118681795(96.6363%)

Read2 after filtering:
total reads: 985779
total bases: 122813977
Q20 bases: 119477723(97.2835%)
Q30 bases: 113201354(92.173%)

Filtering result:
reads passed filter: 1971558
reads failed due to low quality: 28056
reads failed due to too many N: 0
reads failed due to too short: 386
reads with adapter trimmed: 43165
bases trimmed due to adapters: 864517

Duplication rate: 25.143%

Insert size peak (evaluated by paired-end reads): 214

JSON report: data/fastp_reports/SRR31631253.fastp.json
HTML report: data/fastp_reports/SRR31631253.fastp.html

fastp --in1 data/subset_raw/SRR31631253_1.fastq.gz --in2 data/subset_raw/SRR31631253_2.fastq.gz --out1 data/clean/SRR31631253_1.clean.fastq.gz --out2 data/clean/SRR31631253_2.clean.fastq.gz --json data/fastp_reports/SRR31631253.fastp.json --html data/fastp_reports/SRR31631253.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 9 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631260...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123239983(98.592%)
Q30 bases: 120273253(96.2186%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122819830(98.2559%)
Q30 bases: 119219422(95.3755%)

Read1 after filtering:
total reads: 991480
total bases: 123378234
Q20 bases: 121933297(98.8289%)
Q30 bases: 119101531(96.5337%)

Read2 after filtering:
total reads: 991480
total bases: 123379320
Q20 bases: 121710891(98.6477%)
Q30 bases: 118288514(95.8739%)

Filtering result:
reads passed filter: 1982960
reads failed due to low quality: 16366
reads failed due to too many N: 0
reads failed due to too short: 674
reads with adapter trimmed: 66174
bases trimmed due to adapters: 1174878

Duplication rate: 28.7677%

Insert size peak (evaluated by paired-end reads): 180

JSON report: data/fastp_reports/SRR31631260.fastp.json
HTML report: data/fastp_reports/SRR31631260.fastp.html

fastp --in1 data/subset_raw/SRR31631260_1.fastq.gz --in2 data/subset_raw/SRR31631260_2.fastq.gz --out1 data/clean/SRR31631260_1.clean.fastq.gz --out2 data/clean/SRR31631260_2.clean.fastq.gz --json data/fastp_reports/SRR31631260.fastp.json --html data/fastp_reports/SRR31631260.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 9 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631256...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123259071(98.6073%)
Q30 bases: 120352233(96.2818%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122873854(98.2991%)
Q30 bases: 119361449(95.4892%)

Read1 after filtering:
total reads: 991576
total bases: 123447309
Q20 bases: 122020736(98.8444%)
Q30 bases: 119249810(96.5998%)

Read2 after filtering:
total reads: 991576
total bases: 123448443
Q20 bases: 121836518(98.6943%)
Q30 bases: 118489439(95.9829%)

Filtering result:
reads passed filter: 1983152
reads failed due to low quality: 16486
reads failed due to too many N: 0
reads failed due to too short: 362
reads with adapter trimmed: 53486
bases trimmed due to adapters: 1041041

Duplication rate: 28.2522%

Insert size peak (evaluated by paired-end reads): 190

JSON report: data/fastp_reports/SRR31631256.fastp.json
HTML report: data/fastp_reports/SRR31631256.fastp.html

fastp --in1 data/subset_raw/SRR31631256_1.fastq.gz --in2 data/subset_raw/SRR31631256_2.fastq.gz --out1 data/clean/SRR31631256_1.clean.fastq.gz --out2 data/clean/SRR31631256_2.clean.fastq.gz --json data/fastp_reports/SRR31631256.fastp.json --html data/fastp_reports/SRR31631256.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 10 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631252...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123259256(98.6074%)
Q30 bases: 120251022(96.2008%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122806344(98.2451%)
Q30 bases: 119130673(95.3045%)

Read1 after filtering:
total reads: 991430
total bases: 123521235
Q20 bases: 122067219(98.8229%)
Q30 bases: 119182906(96.4878%)

Read2 after filtering:
total reads: 991430
total bases: 123521486
Q20 bases: 121858203(98.6534%)
Q30 bases: 118350182(95.8134%)

Filtering result:
reads passed filter: 1982860
reads failed due to low quality: 16842
reads failed due to too many N: 0
reads failed due to too short: 298
reads with adapter trimmed: 43906
bases trimmed due to adapters: 852207

Duplication rate: 27.0761%

Insert size peak (evaluated by paired-end reads): 201

JSON report: data/fastp_reports/SRR31631252.fastp.json
HTML report: data/fastp_reports/SRR31631252.fastp.html

fastp --in1 data/subset_raw/SRR31631252_1.fastq.gz --in2 data/subset_raw/SRR31631252_2.fastq.gz --out1 data/clean/SRR31631252_1.clean.fastq.gz --out2 data/clean/SRR31631252_2.clean.fastq.gz --json data/fastp_reports/SRR31631252.fastp.json --html data/fastp_reports/SRR31631252.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 9 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631259...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123236890(98.5895%)
Q30 bases: 120242174(96.1937%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122213565(97.7709%)
Q30 bases: 117689467(94.1516%)

Read1 after filtering:
total reads: 988694
total bases: 123141525
Q20 bases: 121680010(98.8131%)
Q30 bases: 118823311(96.4933%)

Read2 after filtering:
total reads: 988694
total bases: 123142016
Q20 bases: 121084003(98.3287%)
Q30 bases: 116781134(94.8345%)

Filtering result:
reads passed filter: 1977388
reads failed due to low quality: 22360
reads failed due to too many N: 0
reads failed due to too short: 252
reads with adapter trimmed: 48654
bases trimmed due to adapters: 923133

Duplication rate: 27.7074%

Insert size peak (evaluated by paired-end reads): 212

JSON report: data/fastp_reports/SRR31631259.fastp.json
HTML report: data/fastp_reports/SRR31631259.fastp.html

fastp --in1 data/subset_raw/SRR31631259_1.fastq.gz --in2 data/subset_raw/SRR31631259_2.fastq.gz --out1 data/clean/SRR31631259_1.clean.fastq.gz --out2 data/clean/SRR31631259_2.clean.fastq.gz --json data/fastp_reports/SRR31631259.fastp.json --html data/fastp_reports/SRR31631259.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 9 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631255...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123202768(98.5622%)
Q30 bases: 120300704(96.2406%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 122874726(98.2998%)
Q30 bases: 119508695(95.607%)

Read1 after filtering:
total reads: 990782
total bases: 123379552
Q20 bases: 121898709(98.7998%)
Q30 bases: 119129569(96.5554%)

Read2 after filtering:
total reads: 990782
total bases: 123381690
Q20 bases: 121814296(98.7296%)
Q30 bases: 118624194(96.1441%)

Filtering result:
reads passed filter: 1981564
reads failed due to low quality: 17976
reads failed due to too many N: 0
reads failed due to too short: 460
reads with adapter trimmed: 50846
bases trimmed due to adapters: 984198

Duplication rate: 23.4104%

Insert size peak (evaluated by paired-end reads): 195

JSON report: data/fastp_reports/SRR31631255.fastp.json
HTML report: data/fastp_reports/SRR31631255.fastp.html

fastp --in1 data/subset_raw/SRR31631255_1.fastq.gz --in2 data/subset_raw/SRR31631255_2.fastq.gz --out1 data/clean/SRR31631255_1.clean.fastq.gz --out2 data/clean/SRR31631255_2.clean.fastq.gz --json data/fastp_reports/SRR31631255.fastp.json --html data/fastp_reports/SRR31631255.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 10 seconds
Detecting adapter sequence for read1...

Cleaning SRR31631251...

>Illumina TruSeq Adapter Read 1
AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

Detecting adapter sequence for read2...
>Illumina TruSeq Adapter Read 2
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

Read1 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123267776(98.6142%)
Q30 bases: 120327878(96.2623%)

Read2 before filtering:
total reads: 1000000
total bases: 125000000
Q20 bases: 123072781(98.4582%)
Q30 bases: 119808620(95.8469%)

Read1 after filtering:
total reads: 992142
total bases: 123620956
Q20 bases: 122185472(98.8388%)
Q30 bases: 119365602(96.5577%)

Read2 after filtering:
total reads: 992142
total bases: 123622776
Q20 bases: 122159665(98.8165%)
Q30 bases: 119045497(96.2974%)

Filtering result:
reads passed filter: 1984284
reads failed due to low quality: 15312
reads failed due to too many N: 0
reads failed due to too short: 404
reads with adapter trimmed: 40429
bases trimmed due to adapters: 840361

Duplication rate: 28.5831%

Insert size peak (evaluated by paired-end reads): 217

Cleaning complete.

JSON report: data/fastp_reports/SRR31631251.fastp.json
HTML report: data/fastp_reports/SRR31631251.fastp.html

fastp --in1 data/subset_raw/SRR31631251_1.fastq.gz --in2 data/subset_raw/SRR31631251_2.fastq.gz --out1 data/clean/SRR31631251_1.clean.fastq.gz --out2 data/clean/SRR31631251_2.clean.fastq.gz --json data/fastp_reports/SRR31631251.fastp.json --html data/fastp_reports/SRR31631251.fastp.html --detect_adapter_for_pe --thread 4
fastp v0.23.4, time used: 9 seconds

Cheack what before and after fastp

In [7]:
report_dir = Path("data/fastp_reports")

rows = []

for report_file in sorted(report_dir.glob("*.json")):
    with open(report_file) as f:
        report = json.load(f)

    before = report["summary"]["before_filtering"]
    after = report["summary"]["after_filtering"]

    rows.append({
        "Sample": report_file.stem.replace(".fastp", ""),
        "Reads before fastp": before["total_reads"],
        "Reads after fastp": after["total_reads"],
        "Reads retained (%)": 100 * after["total_reads"] / before["total_reads"],
    })

fastp_summary = pd.DataFrame(rows)

fastp_summary.round(2)

         Sample  Reads before fastp  Reads after fastp  Reads retained (%)
0   SRR31631251             2000000            1984284               99.21
1   SRR31631252             2000000            1982860               99.14
2   SRR31631253             2000000            1971558               98.58
3   SRR31631254             2000000            1984034               99.20
4   SRR31631255             2000000            1981564               99.08
5   SRR31631256             2000000            1983152               99.16
6   SRR31631257             2000000            1981878               99.09
7   SRR31631258             2000000            1978922               98.95
8   SRR31631259             2000000            1977388               98.87
9   SRR31631260             2000000            1982960               99.15
10  SRR31631261             2000000            1982136               99.11
11  SRR31631262             2000000            1982870               99.14

Get index for kallisto

In [8]:
%%bash

wget https://github.com/pachterlab/kallisto/releases/download/v0.52.0/kallisto_linux-v0.52.0.tar.gz --quiet
wget https://github.com/pachterlab/kallisto-transcriptome-indices/releases/download/v1/human_index_standard.tar.xz --quiet

tar zxvf kallisto_linux-v0.52.0.tar.gz
tar xf human_index_standard.tar.xz

kallisto/
kallisto/test/
kallisto/README.md
kallisto/._kallisto
kallisto/kallisto
kallisto/._license.txt
kallisto/license.txt
kallisto/test/reads_1.fastq.gz
kallisto/test/transcripts.fasta.gz
kallisto/test/sc_reads_2.fastq.gz
kallisto/test/README.md
kallisto/test/._chrom.txt
kallisto/test/chrom.txt
kallisto/test/Snakefile
kallisto/test/reads_2.fastq.gz
kallisto/test/transcripts.gtf.gz
kallisto/test/sc_reads_1.fastq.gz

Try kallisto for 1 sample

In [10]:
%%bash

time kallisto/kallisto quant \
  -i index.idx \
  data/clean/SRR31631251_1.clean.fastq.gz \
  data/clean/SRR31631251_2.clean.fastq.gz \
  -o testing \
  -t 2

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631251_1.clean.fastq.gz
                             data/clean/SRR31631251_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 992,142 reads, 869,926 reads pseudoaligned
[quant] estimated average fragment length: 280.145
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 898 rounds


real	1m5.300s
user	1m29.207s
sys	0m2.932s

Kallisto for all the 12 samples

In [11]:
%%bash

for r1 in data/clean/*_1.clean.fastq.gz
do
    run=$(basename "$r1" _1.clean.fastq.gz)
    r2="data/clean/${run}_2.clean.fastq.gz"

    echo "Running kallisto for $run"

    kallisto/kallisto quant \
        -i index.idx \
        "$r1" \
        "$r2" \
        -o "data/quant/$run" \
        -t 2
done

Running kallisto for SRR31631251

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631251_1.clean.fastq.gz
                             data/clean/SRR31631251_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 992,142 reads, 869,926 reads pseudoaligned
[quant] estimated average fragment length: 280.145
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 898 rounds

Running kallisto for SRR31631252

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631252_1.clean.fastq.gz
                             data/clean/SRR31631252_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 991,430 reads, 870,792 reads pseudoaligned
[quant] estimated average fragment length: 278.292
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 959 rounds

Running kallisto for SRR31631253

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631253_1.clean.fastq.gz
                             data/clean/SRR31631253_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 985,779 reads, 864,860 reads pseudoaligned
[quant] estimated average fragment length: 274.849
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 911 rounds

Running kallisto for SRR31631254

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631254_1.clean.fastq.gz
                             data/clean/SRR31631254_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 992,017 reads, 867,867 reads pseudoaligned
[quant] estimated average fragment length: 276.886
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 921 rounds

Running kallisto for SRR31631255

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631255_1.clean.fastq.gz
                             data/clean/SRR31631255_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 990,782 reads, 863,184 reads pseudoaligned
[quant] estimated average fragment length: 269.214
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 991 rounds

Running kallisto for SRR31631256

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631256_1.clean.fastq.gz
                             data/clean/SRR31631256_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 991,576 reads, 859,195 reads pseudoaligned
[quant] estimated average fragment length: 263.071
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 953 rounds

Running kallisto for SRR31631257

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631257_1.clean.fastq.gz
                             data/clean/SRR31631257_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 990,939 reads, 866,597 reads pseudoaligned
[quant] estimated average fragment length: 264.531
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 1,088 rounds

Running kallisto for SRR31631258

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631258_1.clean.fastq.gz
                             data/clean/SRR31631258_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 989,461 reads, 872,381 reads pseudoaligned
[quant] estimated average fragment length: 266.662
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 935 rounds

Running kallisto for SRR31631259

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631259_1.clean.fastq.gz
                             data/clean/SRR31631259_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 988,694 reads, 843,726 reads pseudoaligned
[quant] estimated average fragment length: 270.473
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 951 rounds

Running kallisto for SRR31631260

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631260_1.clean.fastq.gz
                             data/clean/SRR31631260_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 991,480 reads, 855,190 reads pseudoaligned
[quant] estimated average fragment length: 262.472
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 939 rounds

Running kallisto for SRR31631261

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631261_1.clean.fastq.gz
                             data/clean/SRR31631261_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 991,068 reads, 819,343 reads pseudoaligned
[quant] estimated average fragment length: 271.553
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 965 rounds

Running kallisto for SRR31631262

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 227,665
[index] number of k-mers: 139,900,295
[index] number of D-list k-mers: 5,477,475
[quant] running in paired-end mode
[quant] will process pair 1: data/clean/SRR31631262_1.clean.fastq.gz
                             data/clean/SRR31631262_2.clean.fastq.gz
[quant] finding pseudoalignments for the reads ... done
[quant] processed 991,435 reads, 868,064 reads pseudoaligned
[quant] estimated average fragment length: 269.716
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 915 rounds